export const loadorder = () => `
# This file was automatically generated by Mod Organizer.
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
Unofficial Skyrim Special Edition Patch.esp
ApachiiHair.esm
Campfire.esm
ETaC - RESOURCES.esm
ApachiiHairMales.esm
ApachiiHairFemales.esm
Skyrim Project Optimization - No Homes - Full ESL Version.esm
UHDAP - en0.esp
UHDAP - en1.esp
UHDAP - en2.esp
UHDAP - en3.esp
UHDAP - en4.esp
UHDAP - MusicHQ.esp
FISS.esp
SAS.esl
MajesticMountains_Landscape.esm
MajesticMountains_Moss.esp
Expressive Facegen Morphs.esl
Beards of Power.esp
Landscape and Water Fixes.esp
Lightened Skyrim - merged.esp
SimpleChildren.esp
Treescale.esm
TreescaleSnow.esm
Water for ENB.esm
DynDOLOD.esm
ccBGSSSE001-Fish.esm
High Poly Head.esm
SmoothCam.esl
High Poly Head Vampire Fix.esp
Skyrim Landscape and Water Fixes - Light Sources.esp
Landscape Fixes For Grass Mods.esp
Landscape For Grass Mods - Military Camps.esp
No Riverbededge Grass -Rift -Coast.esp
NotificationLog.esp
Undiscover Skyrim - No Discovery Sounds.esp
UltimateImmersionToggle.esp
No Sun Damage in Soul Cairn.esp
SkyUI_SE.esp
Quest Journal Limit Bug Fixer.esp
AHZmoreHUD.esp
MCMHelper.esp
Realistic-Voice.esp
No NPC Greetings.esp
UnlimitedBookshelves.esp
OnlyOnce.esp
UIExtensions.esp
Autorun.esp
Dynamic Things Alternative.esp
NPC_Overhaul_V_3_.esp
Serana.esp
JaxonzEnhGrab.esp
AMatterOfTime.esp
Customizable Camera.esp
Motion Sensitive Fix SE.esp
chfshVariousActions.esp
TrueDirectionalMovement.esp
Dual Block.esp
reflection-levelupmessages.esp
RealNames - SSE Edition.esp
Immersive Movement Speed.esp
Rische_NoUglyCombatIdlesForVanilla.esp
Wildcat - Combat of Skyrim.esp
ViewableFactionRanks.esp
sandboxcylinderheight.esp
TavernAIFix.esp
dD-No Spinning Death Animation Merged.esp
HonedMetal.esp
HonedMetal-MoreCraftingMaterials.esp
Honed Metal Voiced.esp
TakeNotes.esp
PumpingIron.esp
SkaldsMail.esp
TradeRoutes.esp
Trade & Barter.esp
More Radiant Quests for the Companions.esp
TradeRoutes-Patch-TradeAndBarter.esp
Immersive Speechcraft.esp
TrainAndStudy.esp
Immersive Horses.esp
GIST soul trap.esp
Realistic AI Detection 2 SE - Medium Interior, Medium Exterior.esp
suspiciouscityguards.esp
Hunters Not Bandits.esp
RSBJ.esp
Simply Rest Anywhere.esp
RSF.esp
Keep It Clean.esp
YOT - Keep it Clean.esp
Dirt and Blood - Dynamic Visuals.esp
Dirt and Blood - Keep It Clean Patch.esp
Predator Vision.esp
Hunterborn.esp
Hunterborn - Campfire Patch.esp
Hunterborn - Leather Tanning.esp
Hunterborn - Predator Vision Compatibilty Patch.esp
Underwater_Treasure.esp
RaceMenu.esp
RaceMenuPlugin.esp
SimplyKnock.esp
SpellResearch.esp
SpellResearchRequiem402Patch.esp
Spell Research - Even More Patches.esp
NightEyeENBFix_PredatorVision.esp
Frostfall.esp
Frostfall_Seasonal_Temps_patch.esp
ColdRegionBehavior.esp
Holidays.esp
SleepTight.esp
KN_CuttingTrees.esp
RTSSDNDSS.esp
Chesko_LoreBasedLoadingScreens.esp
SolitudeTempleFrescoes.esp
RentMyHouse.esp
Sanctuary Reborn.esp
Hidden Hideouts of Skyrim - Merged - Deep Immersion.esp
Cidhna Mine Expanded.esp
Weathered Road Signs.esp
BetterQuestObjectives.esp
PaarthurnaxQuestExpansion.esp
TheChoiceIsYours.esp
Guard Dialogue Overhaul.esp
Relationship Dialogue Overhaul.esp
RDO - USSEP Patch.esp
Thieves Guild Requirements.esp
AllThievesGuildJobsConcurrently.esp
PropertiesWithoutPesteringSE.esp
SunHelmSurvival.esp
SunHelmDiseases.esp
SunHelmCampfireSkill.esp
SunHelmForceDisableCold.esp
OCW_Obscure's_CollegeofWinterhold.esp
OCW_CellSettings.esp
ICNs_ImmersiveCollegeNPCs.esp
OCW_MusicPatch_VanillaPlus.esp
OCW_SR_FEPatch.esp
MCWT_ACollegeCoup.esp
MCWT_ACollegeCoup_ICNs_OE.esp
MCWT_ACollegeCoup_OCW.esp
MCWT_ArnielsAppeals.esp
MCWT_DeadDunmerDelivery.esp
MCWT_EarlyElementalist_OCW.esp
ocw door fix.esp
MCWT_ExpiditeTheExpirate.esp
MCWT_GovernableGatekeeper.esp
MCWT_InescapableInsights_EBQO.esp
MCWT_UnflappableFaculty.esp
BA_Bibliophile's_Arcanaeum.esp
SunHelmOCWPatch.esp
SunHelmBAPatch.esp
CoW Entry Requirements.esp
CollegeEntry.esp
CYA_ChooseYourOwnArchMage.esp
Finding_VelehkSain.esp
DeceiveDegaine.esp
LFox Better Thieves Guild Practice Locks.esp
Skyrim Unbound.esp
Skyrim Unbound - Restore Helgen Corridor.esp
Skyrim Unbound - Patch - GDO.esp
Skyrim Unbound - Patch - RDO.esp
Skyrim Unbound - Patch - The Choice Is Yours.esp
Skyrim Unbound - Patch - Trade and Barter.esp
CFTO.esp
CFTO_fix.esp
CFTO-CoveredCarriages.esp
CFTO-Lanterns.esp
hearthfireextended.esp
HFE-CFTO-Patch.esp
SMIM-SE-Merged-All.esp
HoldBorderBanners.esp
CoveredCarriagesSMIM.esp
The Forts of Skyrim-Rebuilt.esp
BetterDocks-MP-DLC-Compatible.esp
BHTNFxyz.esp
HSTNF.esp
VHTNFSSE.esp
hjerimtnf.esp
proudspiremanortnf.esp
Severin Manor.esp
HighHrothgarKitchenSE.esp
OutlawsRefuges.esp
SkyrimSewers.esp
Missives.esp
Missives - Solstheim.esp
Missives - Carriage and Ferry Travel Overhaul Patch.esp
ETaC - Complete.esp
JKs Skyrim.esp
Dawn of Skyrim.esp
JKs Skyrim_Dawn of Skyrim_Patch.esp
JKS_DoS_ETaC_Holidays_Patch.esp
JKS_DoS_OutlawsRefuge_SkyrimSewers_Patch.esp
ETaC - Complete_JKs Skyrim_CFTO Patch.esp
Prometheus_No_snow_Under_the_roof.esp
ETaC - Complete_JKs Skyrim_NSUTR_Patch.esp
SkyHavenTempleGarden.esp
More idle markers.esp
A Lot More Idle Marker.esp
KS Hairdo's.esp
BeastHHBB.esp
HallgarthAdditionalHair.esp
CuyiAntlers.esp
GFoRR.esp
Immersive Patrols II.esp
Immersive Patrols II Simplified.esp
TradeRoutes-Patch-ImmersivePatrols.esp
Inconsequential NPCs.esp
Populated Skyrim Prisons Cells.esp
Faction Crossbows.esp
imp_helm_legend.esp
Book Covers Skyrim.esp
Book Covers Skyrim - Lost Library.esp
BetterQuestObjectives - BCS Patch.esp
OCW_BCS_FEPatch.esp
OCW_BCS-LL_FEPatch.esp
BA_LostLibrary.esp
BA_Sorting_BCS.esp
BA_Sorting_LL.esp
AI Overhaul.esp
Craftable Horse Barding.esp
More_Saddles.esp
alesCampBedrollsSupplies.esp
1nivWICCloaks.esp
Common Clothes and Armors.esp
Weapons Armor Clothing & Clutter Fixes.esp
WACCF_Armor and Clothing Extension.esp
Skyrim Unbound - Patch - WACCF.esp
Complete Crafting Overhaul_Remastered.esp
aMidianBorn_ContentAddon.esp
FranklyHDImperialArmorsAndWeapons.esp
ClothingCraft.esp
OCW_WACCF_FEPatch.esp
OCW_ACE_FEPatch.esp
HFE-Sunhelm Patch.esp
dD - Realistic Ragdoll Force - Realistic.esp
CuyiPriestHoods.esp
XPMSE.esp
Mortal Enemies.esp
QuickLight.esp
Double Wide Quick Light.esp
Fish Anywhere.esp
LokiHorses.esp
CoWDoorBell.esp
Requiem.esp
Requiem - Minor Arcana - Civil War.esp
Requiem - Minor Arcana - Roleplaying.esp
Requiem - Minor Arcana - Vigilants of Stendarr.esp
Fozars_Dragonborn_-_Requiem_Patch.esp
Requiem - Skyrim Sewers.esp
Requiem - WACCF.esp
Requiem - WACCF - ACE.esp
Requiem - CCOR.esp
Requiem - Common Clothes and Armors.esp
Requiem - less double-vision.esp
TradeRoutes-Patch-Requiem.esp
TrainAndStudy - Requiem.esp
Trad_AE_FishingStandalone_Requiem_Patch.esp
hz_NonExploitableCrossbowReload.esp
hz_NECR_ReqPatch_SSE.esp
Requiem - GIST Patch.esp
Remove Interior Fog.esp
SoundsofSkyrimComplete.esp
VioLens SE.esp
DeadlySpellImpacts.esp
DepthsOfSkyrim.esp
Cathedral Weathers.esp
Cathedral Weather Snow Patch.esp
Obsidian Mountain Fogs.esp
RelightingSkyrim_SSE.esp
Landscape and Water Fixes - Patch - Relighting Skyrim.esp
ELE_SSE.esp
SoS_ELE_Patch.esp
Shadows Of Sunlight - In Small Exterior World Spaces.esp
ChillwindDephts.esp
OCW_SoS_FEPatch.esp
OutlawsRefugesProgressionPatch.esp
RASS - Visual Effects.esp
Audio Overhaul Skyrim.esp
Immersive Sounds - Compendium.esp
Skyrim Unbound - Patch - AOS.esp
Audio Overhaul Skyrim - Immersive Sounds Patch.esp
OCW_AO_FEPatch.esp
Improved Combat Sounds v2.2.esp
Immersive Dragon Sounds.esp
No Skeleton Idle Sound.esp
Bird_sound_removed.esp
IHSS.esp
RealisticHuskySoundsSSE.esp
RealisticDogSoundsSSE esl.esp
Torches Ignite Oil - Shock Edition.esp
Laundry.esp
iEquip.esp
dD - Enhanced Blood Main.esp
dD-Reduced Splatter Size.esp
dD-Short Script Range.esp
No More Ugly Effects SE.esp
FacegenForKids.esp
Diverse Character Creation.esp
FollowerLivePackage.esp
HD Lods SSE.esp
aMidianBorn_Buildings Landscapes.esp
Fluffy Snow - BlendedRoads Patch.esp
MajesticMountains.esp
Praedy's Soulcairn.esp
S3DTrees NextGenerationForests.esp
HappyLittleTrees.esp
Folkvangr - Grass and Landscape Overhaul.esp
Origins Of Forest - 3D Forest Grass.esp
Simplicity of Snow.esp
Shaders of Solstheim.esp
WindyGrass.esp
Water for ENB (Shades of Skyrim).esp
Frost Meshes Patch.esp
Embers XD.esp
Embers XD - Patch - JKs Skyrim.esp
Embers XD - Patch - Vanilla Flames.esp
Skyrim Remastered - Soul Gems.esp
Rudy Nordic Pottery SSE.esp
HPP - FirewoodSnow Campfire.esp
HPP - Vaermina's Torpor.esp
GQJ_DG_vampireamuletfix.esp
GDOS - Glorious Solitude Door - Rotation Fix.esp
GDOS - Splendid Mechanized Dwemer Door.esp
Skyland Imperial Forts and Dungeons.esp
VanillaArgoniansRedux.esp
VWA_VanillaWarpaintsAbsolution.esp
Beards for High Poly Head.esp
Brows.esp
Maevan2EyeBrows.esp
SGEyebrows.esp
NB-Scars.esp
TheEyesOfBeauty.esp
The Eyes Of Beauty - Elves Edition.esp
Kala_Eyes.esp
KALA EYES ELVES.esp
Kala_Orsimer Eyes.esp
KALA_BEAST RACE EYES.esp
ENB Light.esp
Rallys Shaggycows of Skyrim.esp
Bears of the North.esp
PraedysSkeletons.esp
Water for ENB - Patch - Expanded Towns and Cities.esp
Water for ENB - Patch - Darker LOD Water.esp
Wildlander.esp
Wildlander_FULL.esp
FNIS.esp
Requiem for the Indifferent.esp
DynDOLOD.esp
Occlusion.esp
DynDOLOD-load-remover.esp
icepenguinworldmapclassic.esp
widescreen_skyui_fix.esp
`;
