export const enum RESOLUTION_EVENTS {
  GET_RESOLUTIONS = "GET_RESOLUTIONS",
  IS_UNSUPPORTED_RESOLUTION = "IS_UNSUPPORTED_RESOLUTION",
  GET_RESOLUTION_PREFERENCE = "GET_RESOLUTION_PREFERENCE",
  SET_RESOLUTION_PREFERENCE = "SET_RESOLUTION_PREFERENCE",
}
