export const enum MOD_ORGANIZER_EVENTS {
  GET_PROFILES = "GET_PROFILES",
  RESTORE_PROFILES = "RESTORE_PROFILES",
  LAUNCH_GAME = "LAUNCH_GAME",
  LAUNCH_MO2 = "LAUNCH_MO2",
  GET_PROFILE_PREFERENCE = "GET_PROFILE_PREFERENCE",
  SET_PROFILE_PREFERENCE = "SET_PROFILE_PREFERENCE",
}
