export const enum GRAPHICS_EVENTS {
  GET_GRAPHICS_PREFERENCE = "GET_GRAPHICS_PREFERENCE",
  GET_GRAPHICS = "GET_GRAPHICS",
  SET_GRAPHICS = "SET_GRAPHICS",
  RESTORE_GRAPHICS = "RESTORE_GRAPHICS",
}
