export const enum ENB_EVENTS {
  GET_ENB_PRESETS = "GET_ENB_PRESETS",
  RESTORE_ENB_PRESETS = "RESTORE_ENB_PRESETS",

  GET_ENB_PREFERENCE = "GET_ENB_PREFERENCE",
  SET_ENB_PREFERENCE = "SET_ENB_PREFERENCE",
}
