export const enum PROFILE_EVENTS {
  GET_PROFILES = "GET_PROFILES",
  GET_PROFILE_PREFERENCE = "GET_PROFILE_PREFERENCE",
  SET_PROFILE_PREFERENCE = "SET_PROFILE_PREFERENCE",
  RESTORE_PROFILES = "RESTORE_PROFILES",
  GET_SHOW_HIDDEN_PROFILES = "GET_SHOW_HIDDEN_PROFILES",
  SET_SHOW_HIDDEN_PROFILES = "SET_SHOW_HIDDEN_PROFILES",
  GET_ENABLE_AUTO_LAUNCH = "GET_ENABLE_AUTO_LAUNCH",
  SET_ENABLE_AUTO_LAUNCH = "SET_ENABLE_AUTO_LAUNCH",
}
