export const enum PROFILE_EVENTS {
  GET_PROFILES = "GET_PROFILES",
  GET_PROFILE_PREFERENCE = "GET_PROFILE_PREFERENCE",
  SET_PROFILE_PREFERENCE = "SET_PROFILE_PREFERENCE",
  RESTORE_PROFILES = "RESTORE_PROFILES",
}
