export const enum SYSTEM_EVENTS {
  OPEN_CRASH_LOGS = "OPEN_CRASH_LOGS",
  OPEN_APPLICATION_LOGS = "OPEN_APPLICATION_LOGS",
  OPEN_LINK_IN_BROWSER = "OPEN_LINK_IN_BROWSER",
  CLEAR_APP_LOGS = "CLEAR_APP_LOGS",
  CHECK_PREREQUISITES = "CHECK_PREREQUISITES",
  INSTALL_PREREQUISITES = "INSTALL_PREREQUISITES",
  REBOOT = "REBOOT",
}
