export const enum MODPACK_EVENTS {
  IS_MODPACK_SET = "IS_MODPACK_SET",
  IS_MODPACK_DIRECTORY_VALID = "IS_MODPACK_DIRECTORY_VALID",
  SET_MODPACK = "SET_MODPACK",
  GET_MODPACK = "GET_MODPACK",
  GET_MODPACK_METADATA = "GET_MODPACK_METADATA",
  DELETE_MODPACK_DIRECTORY = "DELETE_MODPACK_DIRECTORY",
}
