export enum USER_PREFERENCE_KEYS {
  MOD_DIRECTORY = "MOD_DIRECTORY",
  PRESET = "PRESET",
  ENB_PROFILE = "ENB_PROFILE",
  PREVIOUS_ENB_PROFILE = "PREVIOUS_ENB_PROFILE",
  RESOLUTION = "RESOLUTION",
}
